### ISSUE TITLE
Option for generating SVG or PNG

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/badge#18]
@amirm3hdi when giving package name, make an option to select which image format should be presented for the badges.

Currently below are supported:
- png
- svg

**Comment by Alir3z4** [comment]
@amirm3hdi This has been fixed, right ?

**Comment by AmirSavand** [comment]
@Alir3z4 Yea I was gonna close this issue.
Fixed by #27

**Comment by Alir3z4** [comment]
Awesome
thanks for taking care of it ;)

On Mon, Feb 22, 2016 at 8:07 PM, Amir Mehdi Savand <notifications@github.com
