### ISSUE TITLE
Bad font family for badges 

### ISSUE THREAD

**Issue by AmirSavand** [SavandBros/badge#21]
Need to change to: **font-family="DejaVu Sans,Verdana,Geneva,sans-serif"**

**Comment by Alir3z4** [comment]
Good suggestion.
one thing is, we can't set the font family just like that

 each font processing happens in the backend.
So we can only apply one font at the time.

At the moment we only support OpenSans: https://github.com/SavandBros/badge/blob/master/static/fonts/OpenSans-Regular.ttf

Just upload the fonts here so I can take a look and do something about it.

**Comment by Alir3z4** [comment]
Okay, I'm gonna make this happen and shine
